# Generated by Django 4.2 on 2026-07-06 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Center', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
