# Generated by Django 4.2 on 2026-07-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Center', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverer',
            name='phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
