# Generated by Django 4.2.30 on 2026-07-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Center', '0007_order_delivered_at_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverer',
            name='assigned_order',
        ),
    ]
