# Generated by Django 4.2.30 on 2026-07-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Center', '0008_remove_deliverer_assigned_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverer',
            name='assigned_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Center.customer'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
