# Generated by Django 4.2.30 on 2026-07-30 16:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Center', '0010_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliverer_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
